name: Overwrite page_create branch with main

on:
  push:
    branches:
      - main

jobs:
  overwrite-aaaa:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Switch to page_create branch
      run: git checkout page_Create

    - name: Merge main into aaaa
      run: git merge main

    - name: Push changes to page_create branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: page_Create
