  name: Apply JS to Blog HTML and Update page_Create Branch

  on:
    push:
      branches:
        - main  # mainブランチが変更されたとき

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 使用するNode.jsのバージョン

      - name: Install dependencies
        run: npm install node-fetch jsdom

      - name: Apply script to blog HTML
        run: |
          mkdir -p modified_html
          for file in blog/*.html; do
            node script/page_action.cjs "$file" > "modified_html/$(basename "$file")"
          done

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes to page_Create branch
        run: |
          git fetch
          git checkout page_Create
          git add modified_html
          git commit -m "Apply JS to blog HTML"
          git push https://${{secrets.PERSONAL_ACCESS_TOKEN2}}@github.com/aki-com/aki-com.github.io.git HEAD:page_Create
